### ISSUE TITLE
No option for generated CMakeLists.txt location

### ISSUE THREAD

**Issue by Joebeazelman** [modm-io/lbuild#80]
Two issues. First, there's no documentation for **outpath**.  It doesn't appear in the discovery listing as one of the available options.  Second, when specified with a path, it generates the **modm** folder and the **CMakeLists.txt** in the same path. Ideally, there should be an option to specify where the **CMakeLists.txt** file is created.

**Comment by salkinium** [comment]
>  First, there's no documentation for outpath. It doesn't appear in the discovery listing as one of the available options.

Yes, sorry about that. It was added in a bit of a chaotic way in https://github.com/modm-io/modm/pull/645, and then I never got around to properly documenting it.

lbuild knows two paths:

- current working directory (cwd): set by `-C,--cwd PATH`.
- outbasepath: set by `<outpath>` or `-p,--path PATH`.

Files can be generated to and referenced by the cwd and outbasepath through environment translation function.
The use case we wanted to support is to relocate the `modm` out of the application folder via `<outpath>` but then still keep the top-level build system files like `CMakeLists.txt`, `Makefile`, and `SConstruct` in the CWD but with their internal paths pointing to `<outpath>`. Which can be a bit confusing at times to support.

The `<outpath>` is a command line option, rather than a repo/module option, therefore it doesn't show up in the discovery listing.

> Second, when specified with a path, it generates the modm folder and the CMakeLists.txt in the same path.

This may just be a bug in modm rather than lbuild as the [path is controlled by the `modm:build:cmake` module](https://github.com/modm-io/modm/blob/develop/tools/build_script_generator/cmake/module.lb#L203-L205).
The [`modm:build:scons` module places the top-level SConstruct relative to the CWD](https://github.com/modm-io/modm/blob/develop/tools/build_script_generator/scons/module.lb#L245-L247), rather than the outpath.
Perhaps you can hack this and see if that helps you?

**Comment by salkinium** [comment]
This is off-topic due to being an issue in how modm uses lbuild.
